import json

NB_PATH = "/home/sabya/projects/pyspark-dev/notebooks/GradedAssignment.ipynb"

def md(cell_id, lines):
    return {"cell_type": "markdown", "id": cell_id, "metadata": {}, "source": lines}

def code(cell_id, lines):
    return {"cell_type": "code", "execution_count": None, "id": cell_id,
            "metadata": {}, "outputs": [], "source": lines}

new_cells = []

# ─── §9 markdown ────────────────────────────────────────────────────────────
new_cells.append(md("cell-md-s9", [
    "## §9–11 — Transformations & Aggregation\n",
    "\n",
    "> 📌 Assignment Mapping — Part 3, Q1: Narrow vs Wide Dependencies\n",
    "\n",
    "Every transformation you apply to a Spark DataFrame falls into one of two dependency classes,",
    " and knowing which class a transformation belongs to is the single most important thing you",
    " can learn for reasoning about Spark performance.\n",
    "\n",
    "**Narrow dependencies** are transformations where each output partition depends on exactly one",
    " input partition — no data needs to cross the network.\n",
    " `filter`, `select`, `withColumn`, `map`, `flatMap`, and `drop` are all narrow.",
    " Spark can pipeline them together within a single stage, processing them in one pass",
    " without any inter-node communication.\n",
    "\n",
    "**Wide dependencies** are transformations where a single output partition may depend on",
    " *multiple* input partitions — data from different nodes has to be shuffled across the",
    " network and co-located before the operation can complete.\n",
    " `groupBy`, `join`, `distinct`, `repartition`, and `orderBy` are all wide.",
    " Each wide transformation forces a stage boundary: Spark must materialise the shuffle",
    " output before the next stage can begin.\n",
    "\n",
    "The worked example below computes **average engine temperature per vehicle model**.",
    " Every transformation is labelled so the dependency type is never ambiguous.\n",
]))

# ─── §9 code: narrow transforms ─────────────────────────────────────────────
new_cells.append(code("cell-code-s9", [
    "from pyspark.sql import functions as F\n",
    "\n",
    "# Re-use the DataFrame already loaded in §8; reload if kernel was restarted.\n",
    "sdf = (\n",
    "    spark.read\n",
    "    .option(\"header\", \"true\")\n",
    "    .option(\"inferSchema\", \"true\")\n",
    "    .csv(f\"{DATA_DIR}/telemetry_raw.csv\")\n",
    ")\n",
    "\n",
    "# ── NARROW: select ──────────────────────────────────────────────────────────\n",
    "# Keeps only the two columns we need.  Each partition is transformed in place;\n",
    "# no data moves between nodes.  This is a narrow dependency.\n",
    "df_selected = sdf.select(\"vehicle_model\", \"engine_temperature\")  # narrow dependency\n",
    "\n",
    "# ── NARROW: filter ──────────────────────────────────────────────────────────\n",
    "# Discards rows where engine_temperature is outside a plausible operating range.\n",
    "# Applied per-partition with no cross-node communication.  narrow dependency.\n",
    "df_filtered = df_selected.filter(                                  # narrow dependency\n",
    "    (F.col(\"engine_temperature\") >= 60.0) &\n",
    "    (F.col(\"engine_temperature\") <= 120.0)\n",
    ")\n",
    "\n",
    "# ── NARROW: withColumn ──────────────────────────────────────────────────────\n",
    "# Converts Celsius to Fahrenheit, deriving a new column row-by-row in each\n",
    "# partition independently.  narrow dependency.\n",
    "df_with_f = df_filtered.withColumn(                                # narrow dependency\n",
    "    \"engine_temp_f\",\n",
    "    F.round(F.col(\"engine_temperature\") * 9 / 5 + 32, 2)\n",
    ")\n",
    "\n",
    "print(\"Narrow transforms applied: select → filter → withColumn\")\n",
    "print(f\"Partition count after narrow transforms: {df_with_f.rdd.getNumPartitions()}\")\n",
    "df_with_f.printSchema()\n",
]))

# ─── §10 markdown ───────────────────────────────────────────────────────────
new_cells.append(md("cell-md-s10", [
    "## §10 — Wide Dependency: groupBy + Aggregation\n",
    "\n",
    "Now comes the wide transformation.\n",
    "`groupBy(\"vehicle_model\")` must gather all rows that share the same model key onto the",
    " same partition — rows that currently live on different nodes across the cluster.\n",
    " Spark triggers a **shuffle**: every node writes its local `vehicle_model` buckets to",
    " disk, then each reducer node reads its assigned buckets over the network.\n",
    " This is a wide dependency because one output partition depends on *many* input partitions.\n",
    "\n",
    "The `agg(avg(...))` that follows the `groupBy` rides in the same wide stage —",
    " it operates on the already-shuffled data, so it adds no additional shuffle cost.\n",
    " The final `orderBy` is a second wide transformation: sorting requires all nodes to",
    " agree on a global order, which means another shuffle to a single reducer.\n",
]))

# ─── §10 code: wide transform ───────────────────────────────────────────────
new_cells.append(code("cell-code-s10", [
    "# ── WIDE: groupBy + agg ─────────────────────────────────────────────────────\n",
    "# groupBy shuffles all rows with the same vehicle_model key onto the same\n",
    "# partition.  Data crosses the network here.  This is a wide dependency.\n",
    "df_avg_temp = (\n",
    "    df_with_f\n",
    "    .groupBy(\"vehicle_model\")                                      # wide dependency\n",
    "    .agg(\n",
    "        F.round(F.avg(\"engine_temperature\"), 2).alias(\"avg_engine_temp_c\"),\n",
    "        F.round(F.avg(\"engine_temp_f\"), 2).alias(\"avg_engine_temp_f\"),\n",
    "        F.count(\"*\").alias(\"record_count\"),\n",
    "    )\n",
    ")\n",
    "\n",
    "# ── WIDE: orderBy ────────────────────────────────────────────────────────────\n",
    "# Sorting requires a global order across all partitions — another shuffle.\n",
    "# This is a wide dependency.\n",
    "df_avg_temp_sorted = df_avg_temp.orderBy(                          # wide dependency\n",
    "    F.col(\"avg_engine_temp_c\").desc()\n",
    ")\n",
    "\n",
    "print(\"Average engine temperature per vehicle model (°C and °F):\")\n",
    "df_avg_temp_sorted.show(truncate=False)\n",
]))

# ─── §11 markdown + code: dependency summary ────────────────────────────────
new_cells.append(md("cell-md-s11", [
    "## §11 — Dependency Map Summary\n",
    "\n",
    "The full transformation chain above has exactly two stage boundaries — the two points where",
    " a wide dependency forces Spark to materialise a shuffle before continuing:\n",
    "\n",
    "```\n",
    "Stage 1 (pipelined, no shuffle — all narrow dependencies):\n",
    "  read CSV\n",
    "  └─ select(vehicle_model, engine_temperature)          ← narrow dependency\n",
    "  └─ filter(60 ≤ engine_temperature ≤ 120)              ← narrow dependency\n",
    "  └─ withColumn(engine_temp_f)                          ← narrow dependency\n",
    "       [SHUFFLE BOUNDARY]\n",
    "Stage 2 (triggered by groupBy — wide dependency):\n",
    "  └─ groupBy(vehicle_model).agg(avg(...), count(*))     ← wide dependency\n",
    "       [SHUFFLE BOUNDARY]\n",
    "Stage 3 (triggered by orderBy — wide dependency):\n",
    "  └─ orderBy(avg_engine_temp_c DESC)                    ← wide dependency\n",
    "```\n",
    "\n",
    "Narrow dependencies are cheap — Spark pipelines them within a single task and they never",
    " touch the network.\n",
    " Wide dependencies are expensive — each one spills data to disk, transfers it over the",
    " network, and reads it back on the receiving node.\n",
    " In production, the design goal is to push as many narrow dependencies as possible",
    " before the first wide one (so the shuffle operates on a smaller, already-filtered",
    " dataset) and to minimise the total number of wide transformations in the DAG.\n",
]))

new_cells.append(code("cell-code-s11", [
    "# Confirm Spark's physical plan shows two exchange (shuffle) operators,\n",
    "# corresponding to the two wide dependencies identified above.\n",
    "print(\"=== Physical Plan (look for Exchange operators marking shuffle boundaries) ===\")\n",
    "df_avg_temp_sorted.explain(mode=\"formatted\")\n",
]))

# ─── §13 markdown ───────────────────────────────────────────────────────────
new_cells.append(md("cell-md-s13", [
    "## §13 — Data Skew\n",
    "\n",
    "> 📌 Assignment Mapping — Part 3, Q2: Salting Strategy for Data Skew\n",
    "\n",
    "The §8 output already showed the pathology: VH_0000 through VH_0009 each produce",
    " **1000x more logs** than any other vehicle_id in the fleet.\n",
    " That skew ratio was baked in deliberately — it is the exact scenario this question asks",
    " you to diagnose and fix.\n",
    "\n",
    "### Why Skew Kills a groupBy\n",
    "\n",
    "When you run `groupBy(\"vehicle_id\")` on a skewed dataset, Spark's hash partitioner assigns",
    " all rows for a given key to the same partition.\n",
    " The 10 hot vehicles end up dominating 10 partitions, while the other 490 partitions each",
    " hold only 95 rows.\n",
    " The job's wall-clock time is determined by the slowest task — the one processing 95,000",
    " rows — while every other task finishes almost instantly and sits idle.\n",
    " This is the skew tax: you're paying for a cluster-sized job but getting single-task throughput.\n",
    "\n",
    "### Hash vs Range Partitioning\n",
    "\n",
    "Before fixing the skew, it's worth being explicit about **Hash vs Range** partitioning,",
    " because the choice of partitioner determines how bad the skew actually is:\n",
    "\n",
    "- **Hash partitioning** (Spark's default for `groupBy`): assigns each row to a partition",
    "  based on `hash(key) % numPartitions`.",
    "  For a uniform key distribution this works well.",
    "  For a skewed key like `vehicle_id`, it concentrates all rows of a hot key onto one",
    "  partition deterministically — the worst possible outcome for skew.\n",
    "- **Range partitioning** (used by `orderBy`/`sortBy`): divides the key space into",
    "  contiguous ranges and assigns a range to each partition.",
    "  This is the right choice when keys have a natural sort order and you need sorted output.",
    "  For `vehicle_id` there is no meaningful ordering to exploit — VH_0000 is not",
    "  \"closer\" to VH_0001 than to VH_0499 in any analytical sense.",
    "  Range partitioning would not help here and would add sampling overhead for no gain.\n",
    "\n",
    "**Hash partitioning is the correct choice** for this `groupBy` — but we need to break",
    " the skew by changing what we hash on, not by switching the partitioner.\n",
    " That is exactly what salting does.\n",
    "\n",
    "### The Salting Strategy\n",
    "\n",
    "Salting appends a random integer suffix to the skewed key before the `groupBy`,",
    " spreading what was one partition's worth of data across N partitions.",
    " After the first aggregation, the salt is stripped and partial results are combined",
    " in a second aggregation on the original key.\n",
    " The two-pass approach is the price of breaking the skew — but both passes are far",
    " cheaper than the single-pass skewed shuffle was.\n",
]))

# ─── §13 code: before salting ───────────────────────────────────────────────
new_cells.append(code("cell-code-s13-before", [
    "import matplotlib\n",
    "matplotlib.use('Agg')\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# ── BEFORE salting: measure per-partition record counts ──────────────────────\n",
    "# glom() collapses each partition into a list; map(len) gives its row count.\n",
    "# This makes the imbalance concrete — not asserted, but measured.\n",
    "sdf_vehicle = (\n",
    "    spark.read\n",
    "    .option(\"header\", \"true\")\n",
    "    .option(\"inferSchema\", \"true\")\n",
    "    .csv(f\"{DATA_DIR}/telemetry_raw.csv\")\n",
    ")\n",
    "\n",
    "partition_counts_before = sdf_vehicle.rdd.glom().map(len).collect()\n",
    "partition_counts_before_sorted = sorted(partition_counts_before, reverse=True)\n",
    "\n",
    "print(\"=== Per-partition row counts BEFORE salting ===\")\n",
    "print(f\"Num partitions : {len(partition_counts_before)}\")\n",
    "print(f\"Max partition  : {max(partition_counts_before):,}  rows\")\n",
    "print(f\"Min partition  : {min(partition_counts_before):,}  rows\")\n",
    "print(f\"Skew ratio     : {max(partition_counts_before)/max(min(partition_counts_before),1):.1f}x\")\n",
    "print(f\"All counts     : {partition_counts_before_sorted}\")\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(8, 3))\n",
    "ax.bar(range(len(partition_counts_before_sorted)), partition_counts_before_sorted, color='#d9534f')\n",
    "ax.set_title('Per-Partition Row Counts — BEFORE Salting')\n",
    "ax.set_xlabel('Partition index (sorted desc)')\n",
    "ax.set_ylabel('Row count')\n",
    "plt.tight_layout()\n",
    "plt.savefig(f\"{OUTPUT_DIR}/skew_before.png\", dpi=100)\n",
    "plt.show()\n",
    "print(f\"Chart saved to {OUTPUT_DIR}/skew_before.png\")\n",
]))

# ─── §13 code: salting implementation ───────────────────────────────────────
new_cells.append(code("cell-code-s13-salt", [
    "import os\n",
    "os.makedirs(OUTPUT_DIR, exist_ok=True)\n",
    "\n",
    "SALT_BUCKETS = 10  # spread each hot key across 10 partitions\n",
    "\n",
    "# ── Step 1: append a random salt suffix to vehicle_id ───────────────────────\n",
    "# This turns one hot key (e.g. 'VH_0000') into 10 salted keys\n",
    "# ('VH_0000_0' … 'VH_0000_9'), distributing its 95,000 rows across\n",
    "# 10 partitions instead of 1.\n",
    "df_salted = sdf_vehicle.withColumn(\n",
    "    \"vehicle_id_salted\",\n",
    "    F.concat(\n",
    "        F.col(\"vehicle_id\"),\n",
    "        F.lit(\"_\"),\n",
    "        (F.rand(seed=42) * SALT_BUCKETS).cast(\"int\").cast(\"string\")\n",
    "    )\n",
    ")\n",
    "\n",
    "# ── Step 2: first aggregation on the salted key (wide dependency) ───────────\n",
    "# Shuffle now operates on salted keys — the hot vehicle's rows are spread\n",
    "# across 10 partitions, each handling ~9,500 rows instead of 95,000.\n",
    "df_partial = (\n",
    "    df_salted\n",
    "    .groupBy(\"vehicle_id_salted\", \"vehicle_id\")          # wide dependency\n",
    "    .agg(\n",
    "        F.sum(\"distance_km\").alias(\"partial_distance_km\"),\n",
    "        F.count(\"*\").alias(\"partial_count\"),\n",
    "    )\n",
    ")\n",
    "\n",
    "# ── Step 3: de-salt — strip the suffix and combine partial results ───────────\n",
    "# Second groupBy on the original vehicle_id; each key now has at most\n",
    "# SALT_BUCKETS rows coming in, so this shuffle is tiny.\n",
    "df_final = (\n",
    "    df_partial\n",
    "    .groupBy(\"vehicle_id\")                                # wide dependency (de-salt)\n",
    "    .agg(\n",
    "        F.sum(\"partial_distance_km\").alias(\"total_distance_km\"),\n",
    "        F.sum(\"partial_count\").alias(\"total_count\"),\n",
    "    )\n",
    "    .orderBy(F.col(\"total_distance_km\").desc())\n",
    ")\n",
    "\n",
    "print(\"=== Top 15 vehicles by total distance (after salting) ===\")\n",
    "df_final.show(15, truncate=False)\n",
]))

# ─── §13 code: after salting partition check ────────────────────────────────
new_cells.append(code("cell-code-s13-after", [
    "# ── AFTER salting: repeat the glom partition-count check ────────────────────\n",
    "partition_counts_after = df_salted.rdd.glom().map(len).collect()\n",
    "partition_counts_after_sorted = sorted(partition_counts_after, reverse=True)\n",
    "\n",
    "print(\"=== Per-partition row counts AFTER adding salt column ===\")\n",
    "print(f\"Num partitions : {len(partition_counts_after)}\")\n",
    "print(f\"Max partition  : {max(partition_counts_after):,}  rows\")\n",
    "print(f\"Min partition  : {min(partition_counts_after):,}  rows\")\n",
    "print(f\"Skew ratio     : {max(partition_counts_after)/max(min(partition_counts_after),1):.1f}x\")\n",
    "\n",
    "# ── Side-by-side comparison ──────────────────────────────────────────────────\n",
    "print(\"\\n=== Before vs After (sorted partition sizes) ===\")\n",
    "print(f\"{'Partition':<12} {'Before':>10} {'After':>10}\")\n",
    "for i, (b, a) in enumerate(zip(partition_counts_before_sorted,\n",
    "                                partition_counts_after_sorted)):\n",
    "    print(f\"{i:<12} {b:>10,} {a:>10,}\")\n",
    "\n",
    "fig, axes = plt.subplots(1, 2, figsize=(12, 3), sharey=False)\n",
    "axes[0].bar(range(len(partition_counts_before_sorted)),\n",
    "            partition_counts_before_sorted, color='#d9534f')\n",
    "axes[0].set_title('BEFORE Salting')\n",
    "axes[0].set_xlabel('Partition (sorted desc)')\n",
    "axes[0].set_ylabel('Row count')\n",
    "axes[1].bar(range(len(partition_counts_after_sorted)),\n",
    "            partition_counts_after_sorted, color='#5cb85c')\n",
    "axes[1].set_title('AFTER Salting')\n",
    "axes[1].set_xlabel('Partition (sorted desc)')\n",
    "plt.suptitle('Per-Partition Row Counts: Skew Before vs After Salting')\n",
    "plt.tight_layout()\n",
    "plt.savefig(f\"{OUTPUT_DIR}/skew_comparison.png\", dpi=100)\n",
    "plt.show()\n",
    "print(f\"Chart saved to {OUTPUT_DIR}/skew_comparison.png\")\n",
]))

# ─── §14 markdown ───────────────────────────────────────────────────────────
new_cells.append(md("cell-md-s14", [
    "## §14–15 — RDD Lineage & Fault Tolerance\n",
    "\n",
    "> 📌 Assignment Mapping — Part 3, Q3: Fault Tolerance via RDD Lineage\n",
    "\n",
    "Spark's fault tolerance story is unusual in distributed computing because it does not",
    " rely on replicating data to survive node failures.",
    " Understanding why requires understanding two design decisions that Spark baked in from",
    " the start: immutability and lineage.\n",
    "\n",
    "### RDDs Are Immutable\n",
    "\n",
    "Every RDD (and by extension every DataFrame, which is built on top of an RDD) is",
    " **immutable** — once created, its contents never change.",
    " Transformations don't modify an existing RDD; they produce a new one.",
    " `df.filter(...)` returns a new DataFrame that describes the filtered result;",
    " the original `df` is unchanged.\n",
    "\n",
    "Immutability has a critical consequence: Spark never has to worry about a partially-written",
    " or corrupted intermediate state.",
    " If a computation is interrupted mid-way, the input data is still exactly as it was",
    " before the interrupted transformation started.\n",
    "\n",
    "### Lineage: The DAG as a Recovery Plan\n",
    "\n",
    "When you chain transformations — `read → filter → withColumn → groupBy → agg` — Spark",
    " does not execute them immediately.",
    " Instead, it records the sequence as a **lineage graph** (a DAG of transformation steps)",
    " and defers execution until an action (like `.collect()` or `.show()`) is called.\n",
    "\n",
    "That lineage graph is Spark's recovery plan.",
    " If a node fails mid-execution and a partition is lost, Spark doesn't need to restore",
    " it from a replica — it just re-runs the lineage for that partition on another node,",
    " starting from the last stable input.\n",
    "\n",
    "This is how Spark achieves **fault tolerance** **without heavy data replication**:",
    " instead of keeping two or three physical copies of every partition on disk at all times",
    " (the HDFS approach), Spark keeps one logical description of how to reconstruct any",
    " partition from scratch.",
    " Storage cost is O(lineage depth), not O(data size × replication factor).\n",
    "\n",
    "The trade-off is that reconstruction time grows with lineage depth.",
    " For a two-step pipeline, re-running from the source is trivial.",
    " For a 200-step iterative pipeline, re-running from scratch after a node failure is",
    " expensive — which is exactly the problem that checkpointing (§16) solves.\n",
]))

# ─── §15 code: lineage visualisation ────────────────────────────────────────
new_cells.append(md("cell-md-s15", [
    "## §15 — Lineage in Action\n",
    "\n",
    "The code below builds a short transformation chain and then prints the lineage",
    " (`toDebugString`) so you can see the DAG structure as Spark records it.",
    " Notice that nothing executes until the final `.count()` action — all the",
    " transformations before it are just nodes in the lineage graph.\n",
]))

new_cells.append(code("cell-code-s15", [
    "# Build a deliberate 4-step transformation chain to make the lineage visible.\n",
    "df_step1 = sdf_vehicle.filter(F.col(\"speed\") > 0)               # narrow\n",
    "df_step2 = df_step1.withColumn(                                   # narrow\n",
    "    \"speed_ms\", F.round(F.col(\"speed\") / 3.6, 4)\n",
    ")\n",
    "df_step3 = df_step2.filter(F.col(\"battery_efficiency\") > 0.7)    # narrow\n",
    "df_step4 = df_step3.groupBy(\"vehicle_model\").agg(                 # wide\n",
    "    F.avg(\"speed_ms\").alias(\"avg_speed_ms\"),\n",
    "    F.count(\"*\").alias(\"n\")\n",
    ")\n",
    "\n",
    "print(\"=== RDD Lineage (toDebugString) ===\")\n",
    "print(df_step4.rdd.toDebugString().decode())\n",
    "\n",
    "# Action triggers execution of the entire lineage.\n",
    "result_count = df_step4.count()\n",
    "print(f\"\\nAction triggered — {result_count} rows produced.\")\n",
    "print(\"If any partition had failed during this action, Spark would have\")\n",
    "print(\"re-run only the failed partition's lineage on another node — \")\n",
    "print(\"fault tolerance without heavy data replication.\")\n",
]))

# ─── §16 markdown ───────────────────────────────────────────────────────────
new_cells.append(md("cell-md-s16", [
    "## §16 — Liability of Lineage & Checkpointing\n",
    "\n",
    "> 📌 Assignment Mapping — Part 3, Q4: Checkpointing to Prevent StackOverflow\n",
    "\n",
    "Lineage is Spark's recovery superpower — but it has a liability that only shows up in",
    " iterative workloads, and it can kill your job in a way that's genuinely surprising the",
    " first time you hit it.\n",
    "\n",
    "Every transformation appends a new node to the lineage DAG.",
    " For a short pipeline that DAG is a few nodes deep and costs almost nothing to maintain.",
    " For an iterative loop — say, 50 rounds of feature engineering where each round builds",
    " on the previous DataFrame — the DAG grows one level deeper per iteration.",
    " After 50 iterations the lineage is 50 nodes deep; after 200 it is 200 nodes deep.\n",
    "\n",
    "Two problems compound as the DAG grows:\n",
    "\n",
    "1. **StackOverflow errors** — Spark's DAG scheduler recurses through the lineage graph",
    "   to plan execution.",
    "   A sufficiently deep lineage graph overflows the JVM call stack and crashes the driver",
    "   with a `StackOverflow` error — not an out-of-memory error, not a timeout, a stack",
    "   overflow.",
    "   This is one of the most confusing Spark failures because nothing about the error",
    "   message obviously points to lineage depth.\n",
    "2. **Recovery time grows with depth** — if a node fails late in a 200-iteration run,",
    "   Spark must replay the entire 200-step lineage to reconstruct the lost partition.",
    "   The longer the lineage, the more work a failure forces.\n",
    "\n",
    "### Checkpointing Truncates the DAG\n",
    "\n",
    "`df.checkpoint()` materialises the DataFrame to the checkpoint directory",
    " (set in the bootstrap cell as `CHECKPOINT_DIR`) and **severs the lineage**.",
    " The checkpointed DataFrame's parent is the checkpoint file on disk, not the chain of",
    " transformations that produced it.",
    " All history before the checkpoint is forgotten from Spark's perspective.\n",
    "\n",
    "Called every N iterations, checkpointing keeps the lineage depth bounded at N nodes",
    " regardless of how many total iterations run.",
    " This prevents **StackOverflow errors** and **stabilizes recovery time**: a failure",
    " at any point only requires replaying back to the most recent checkpoint, not back",
    " to the beginning of the job.\n",
    "\n",
    "*(The deeper comparison between `.checkpoint()` and `.cache()/.persist()` —",
    " when each is appropriate, and what they cost — is in §16b, Part 4 Q3.)*\n",
]))

# ─── §16 code: deep lineage + checkpoint ────────────────────────────────────
new_cells.append(code("cell-code-s16", [
    "import os\n",
    "os.makedirs(CHECKPOINT_DIR, exist_ok=True)\n",
    "\n",
    "ITERATIONS   = 40   # enough to build a visibly deep lineage\n",
    "CKPT_EVERY   = 10   # checkpoint every 10 iterations to bound DAG depth\n",
    "\n",
    "# Start from a clean, cached baseline so I/O doesn't dominate the timing.\n",
    "df_iter = (\n",
    "    spark.read\n",
    "    .option(\"header\", \"true\")\n",
    "    .option(\"inferSchema\", \"true\")\n",
    "    .csv(f\"{DATA_DIR}/telemetry_raw.csv\")\n",
    "    .select(\"vehicle_id\", \"vehicle_model\", \"engine_temperature\",\n",
    "            \"battery_efficiency\", \"distance_km\")\n",
    "    .cache()   # cache the source; iterations build on top of it\n",
    ")\n",
    "df_iter.count()  # materialise cache\n",
    "\n",
    "print(f\"Simulating {ITERATIONS} iterative feature-engineering passes ...\")\n",
    "print(f\"Checkpoint every {CKPT_EVERY} iterations.\\n\")\n",
    "\n",
    "for i in range(1, ITERATIONS + 1):\n",
    "    # Each iteration adds two narrow transformations to the lineage.\n",
    "    df_iter = df_iter.withColumn(\n",
    "        \"engine_temperature\",\n",
    "        F.round(F.col(\"engine_temperature\") * 0.9999 + 0.001, 4)\n",
    "    )\n",
    "    df_iter = df_iter.withColumn(\n",
    "        \"distance_km\",\n",
    "        F.round(F.col(\"distance_km\") + 0.001, 4)\n",
    "    )\n",
    "\n",
    "    if i % CKPT_EVERY == 0:\n",
    "        # Show lineage depth just BEFORE checkpointing.\n",
    "        debug_str = df_iter.rdd.toDebugString().decode()\n",
    "        depth = debug_str.count(\"MapPartitionsRDD\")\n",
    "        print(f\"Iteration {i:3d} | lineage depth ~ {depth} nodes  → checkpointing ...\")\n",
    "        df_iter = df_iter.checkpoint()   # truncate the DAG here\n",
    "        debug_after = df_iter.rdd.toDebugString().decode()\n",
    "        depth_after = debug_after.count(\"MapPartitionsRDD\")\n",
    "        print(f\"             | lineage depth after checkpoint: {depth_after} nodes\")\n",
    "\n",
    "print(\"\\nFinal lineage (post-checkpoint — should be shallow):\")\n",
    "print(df_iter.rdd.toDebugString().decode())\n",
    "\n",
    "print(\"\\nSample of final DataFrame values after iterative updates:\")\n",
    "df_iter.show(5, truncate=False)\n",
]))

# ─── Load notebook, append cells, save ──────────────────────────────────────
with open(NB_PATH) as f:
    nb = json.load(f)

nb["cells"].extend(new_cells)

with open(NB_PATH, "w") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"Done. Notebook now has {len(nb['cells'])} cells.")
